import {BASKET_ROUTE, BRAND_ROUTE, DEVICE_ROUTE, RATING_ROUTE, TYPE_ROUTE} from "./deviceRoutes";
import {USER_ROUTE} from "./userRoutes";
import {ORDER_ROUTE} from "./orderRoutes";

export const API_ROUTE = 'api'

export const USER_API_ROUTE = API_ROUTE + USER_ROUTE
export const BASKET_API_ROUTE = API_ROUTE + BASKET_ROUTE
export const DEVICE_API_ROUTE = API_ROUTE + DEVICE_ROUTE
export const TYPE_API_ROUTE = API_ROUTE + TYPE_ROUTE
export const BRAND_API_ROUTE = API_ROUTE + BRAND_ROUTE
export const RATING_API_ROUTE = API_ROUTE + RATING_ROUTE
export const ORDER_API_ROUTE = API_ROUTE + ORDER_ROUTE